release: Build static binaries
Currently, both the CLI and controller builds produce binaries that link
against libc. This necessitates that runtime dependencies be provided by
the operating system (or container base image).

This change updates the build to produce static binaries that are
linkerd against MUSL instead of GNU libc. This change also updates the
build to link against a vendored version of OpenSSL, so that the OpenSSL
version is pinned at build-time.

To do so, this change:

- Updates the devcontainer to v33, which includes a variety of
  build/test utilties.
- Adds a `justfile` that includes recipes for buildling (and
  cross-compiling) CLI binaries
- Moves the `linkerd-failover-cli` binary so that it is built as
  `linkerd-failover` (which is how it should actually be invoked by
  users).
- Removes the local 'docker-build' action, which is copied from the
  Linkerd2 repo.
- Updates CI checks to validate devcontainer images (instead of rust
  toolchains)

See https://github.com/linkerd/dev/pull/13

Signed-off-by: Oliver Gould <ver@buoyant.io>

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -1,61 +1,68 @@
 name: Integration tests
 
+# TODO(ver) the integration test cases should not be enumerated in the workflow,
+# but invoked via a general test runner.
+
 on: [pull_request]
 
 permissions:
   contents: read
 
-env:
-  DOCKER_REGISTRY: ghcr.io/linkerd
-  ARCHIVES: /home/runner/archives
-
 jobs:
-
   docker-build:
     runs-on: ubuntu-20.04
-    timeout-minutes: 10
+    container: ghcr.io/linkerd/dev:v33-tools
+    timeout-minutes: 15
     steps:
-    - name: Checkout code
-      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
-    - name: Docker build
-      uses: ./.github/actions/docker-build
+    - run: apt update && apt install -y docker.io
+    - uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25
+    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
+    - uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
       with:
-        docker-registry: ${{ env.DOCKER_REGISTRY }}
-        docker-tag: ${{ github.sha }}
-        docker-target: linux-amd64
-        component: failover
-    - name: Create artifact with image
+        path: /home/runner/buildx-cache
+        key: ${{ runner.os }}-buildx-failover
+    - name: Run just controller-build-image
       run: |
-        mkdir -p ${{ env.ARCHIVES }}
-        docker save "${{ env.DOCKER_REGISTRY}}/failover:${{ github.sha }}" > ${{ env.ARCHIVES }}/failover.tar
-    - name: Upload artifact
-      uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
+        mkdir -p /home/runner/images
+        just controller-build-image \
+          --tag 'ghcr.io/linkerd/failover:git-${{ github.sha }}' \
+          --output 'type=docker' \
+          --cache-from 'type=local,src=/home/runner/buildx-cache' \
+          --cache-to 'type=local,dest=/home/runner/buildx-cache,mode=max'
+        docker save \
+          --output /home/runner/images/controller.tar \
+          'ghcr.io/linkerd/failover:git-${{ github.sha }}'
+    - run: action-docker-prune /home/runner/buildx-cache
+    - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
       with:
-        name: image-archives
-        path: ${{ env.ARCHIVES }}
+        name: images
+        path: /home/runner/images
 
   install-test:
     runs-on: ubuntu-20.04
-    timeout-minutes: 10
+    timeout-minutes: 15
     needs: [docker-build]
     steps:
-    - name: Checkout code
-      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
-    - name: Set up Helm
-      uses: azure/setup-helm@f382f75448129b3be48f8121b9857be18d815a82
-    - name: Create cluster
-      uses: AbsaOSS/k3d-action@b176c2a6dcae72e3e64e3e4d61751904ec314002
+    - uses: azure/setup-helm@f382f75448129b3be48f8121b9857be18d815a82
+    - uses: AbsaOSS/k3d-action@b176c2a6dcae72e3e64e3e4d61751904ec314002
       with:
-        cluster-name: testing
-    - name: Download image
-      uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
+        cluster-name: default
+
+    - uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
       with:
-        name: image-archives
-        path: image-archives
-    - name: Load image
-      run: docker load < image-archives/failover.tar
-    - name: Import image
-      run: k3d image import image-archives/failover.tar -c testing
+        name: images
+        path: /home/runner/images
+    - name: Run k3d image import
+      run: |
+        # This can be flakey so retry it a few times.
+        for _ in {0..2} ; do
+          if k3d image import --mode=direct --cluster=default /home/runner/images/controller.tar ; then
+            exit 0
+          fi
+          sleep 5
+        done
+        exit 1
+
     - name: Install linkerd
       run: |
         curl -sL https://run.linkerd.io/install-edge | sh
@@ -68,12 +75,14 @@ jobs:
         helm repo add linkerd-smi https://linkerd.github.io/linkerd-smi
         helm repo up
         helm install linkerd-smi -n linkerd-smi --create-namespace --wait linkerd-smi/linkerd-smi
+    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
     - name: Install current linkerd-failover
       run: |
         helm install linkerd-failover -n linkerd-failover --create-namespace --wait \
-          --set image.registry=${{ env.DOCKER_REGISTRY }} \
-          --set image.tag=${{ github.sha }} \
+          --set image.registry=ghcr.io/linkerd \
+          --set image.tag=git-${{ github.sha }} \
           charts/linkerd-failover
+
     - name: Test routing to primary
       uses: ./.github/actions/failover-test
       with:
